name: Copy HTML Folder from master to SharedFiles

on:
  push:
    branches:
      - master  # Trigger the workflow when there is a commit to the 'master' branch

jobs:
  copy-folder:
    runs-on: ubuntu-latest

    steps:
      # Checkout the master branch (where the HTML folder exists)
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master

      # Set up Git configuration for commit
      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      # Ensure SharedFiles branch exists, or create it if it doesn't
      - name: Create and checkout SharedFiles branch if it doesn't exist
        run: |
          # Fetch all branches
          git fetch origin

          # Check if the SharedFiles branch exists
          if git show-ref --verify --quiet refs/heads/SharedFiles; then
            git checkout SharedFiles  # If the branch exists, checkout the branch
          else
            # If the branch doesn't exist, create it from the master branch
            git checkout -b SharedFiles
            git push origin SharedFiles  # Push the new branch to remote
          fi

      # Copy the HTML folder to SharedFiles branch
      - name: Copy HTML folder to SharedFiles branch
        run: |
          # Copy the HTML folder to the SharedFiles branch
          cp -r HTML/ HTML/

          # Add the changes to git
          git add HTML/

          # Commit the changes
          git commit -m "Copy HTML folder from master to SharedFiles"

          # Push the changes to the SharedFiles branch using the personal access token
          git push https://github.com/D-Clerk/davidclerk.git SharedFiles --force
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the token from secrets
